
        instr 1
; list of min and max for the mappable parameters
   chnset 0.0, "parm1_min" 
   chnset 1.0, "parm1_max" 
   chnset 0.0, "parm2_min" 
   chnset 1.0, "parm2_max" 
   chnset 0.0, "parm3_min" 
   chnset 1.0, "parm3_max" 
   chnset 0.0, "parm4_min" 
   chnset 1.0, "parm4_max" 
   chnset 0.0, "parm5_min" 
   chnset 1.0, "parm5_max" 
   chnset 0.0, "parm6_min" 
   chnset 1.0, "parm6_max" 
   chnset 0.0, "parm7_min" 
   chnset 1.0, "parm7_max" 
   chnset 0.0, "parm8_min" 
   chnset 1.0, "parm8_max" 
                        
        endin
